Repository proyecto-2021/program-repair-golf, pull requests merged in 2021-10, with the labels that each got.

#3 Create Auth Blueprint.
  app/__init__.py
  app/auth/__init__.py
  app/auth/views.py
Labels: Team 0

#5 Install SQLAlchemy & configure migration on it
  app/__init__.py
  app/models.py
  migrations/README
  migrations/alembic.ini
  migrations/script.py.mako
  migrations/versions/c5e2edffb6f2_initial_migration.py
  requirements.txt
Labels: Team 0

#45 Ruby Blueprint created. Ref #14
  app/__init__.py
  app/ruby/__init__.py
  app/ruby/views.py
Labels: Team 1

#49 Solve migration problem. Ref #48
  migrations/versions/0cb84c718ecc_create_rubychallenge_model.py
Labels: Team 1

#61 25 Create-Model-Go
  app/__init__.py
  app/go/models_go.py
Labels: Team 6

#63 Solution migration
  app/javascript/models_js.py
  migrations/versions/5d1b887ff54f_create_model_javascriptchallenge.py
Labels: Team 4

#64 51 create python model
  app/__init__.py
  app/python/models.py
  migrations/versions/785a27199c86_create_pythonchallenge_model.py
  migrations/versions/d6c9367fa8a8_merging_javascriptchallenge_and_.py
Labels: team 5

#69 solved migration and updated model javascript Ref #68
  app/javascript/models_js.py
  migrations/versions/47a356299a25_.py
  migrations/versions/5d1b887ff54f_create_model_javascriptchallenge.py
Labels: Team 4

#70 Add method get_dict to ruby model. Ref #11
  app/ruby/models.py
Labels: Team 1

#75 Create go challenge model
  migrations/versions/a30ab1db83b4_create_go_challenge_model.py
Labels: Team 6

#82 Add new directory for save files
  .gitignore
  public/challenges/README.md
Labels: Team 1

#95 Add a new function. #89
  app/go/models_go.py
Labels: Team 6

#100 99-js-upload-files-method Ref #99
  app/javascript/files_js.py
Labels: Team 4

#107 19 get csharp challenges
  app/cSharp/views.py
Labels: Team 2

#126 112 js update post javascript challenge
  app/javascript/create_challenge.py
  app/javascript/files_js.py
Labels: Team 4

#128 Add dependence to calculate edit distance. Ref #127
  requirements.txt
Labels: Team 1

#132 Return update, returning the content of code and test of JS files. Re…
  app/javascript/create_challenge.py
Labels: Team 4

#146 145 modularize file methods for python views
  app/python/file_utils.py
  app/python/views.py
Labels: team 5

#178 Fix misspelling
  migrations/versions/a30ab1db83b4_create_go_challenge_model.py
Labels: Team 6

#179 116 ruby modularize file management
  app/ruby/RubyChallengeAPI.py
  app/ruby/filemanagement.py
  app/ruby/models.py
Labels: Team 1

#184 98 fix python challenge update
  app/python/file_utils.py
  app/python/views.py
Labels: team 5

#185 141 ruby endpoints testing
  app/ruby/RubyChallengeAPI.py
  tests/ruby/run-ruby-tests.sh
  tests/ruby/test_rest_api.py
  tests/ruby/tests-data/example1.rb
  tests/ruby/tests-data/example2.rb
  tests/ruby/tests-data/example3.rb
  tests/ruby/tests-data/example4.rb
  tests/ruby/tests-data/example5.rb
  tests/ruby/tests-data/example_fixed4.rb
  tests/ruby/tests-data/example_put5.rb
  tests/ruby/tests-data/example_test1.rb
  tests/ruby/tests-data/example_test2.rb
  tests/ruby/tests-data/example_test3.rb
  tests/ruby/tests-data/example_test4.rb
  tests/ruby/tests-data/example_test5.rb
  tests/ruby/tests-data/example_test_put5.rb
Labels: Team 1

#188 fix in post java. #187
  app/java/lib/hamcrest-all-1.3.jar
  app/java/views.py
Labels: Team 3

#190 Created module command and exception. Ref #181
  app/javascript/exceptions/CommandRunException.py
  app/javascript/modules/command_module.py
Labels: Team 4
