Repository proyecto-2021/program-repair-golf, pull requests merged in 2021-11, with the labels that each got.

#207 203 ruby test special cases of post endpoint
  app/ruby/controller.py
  tests/ruby/test_rest_api.py
  tests/ruby/tests-data/example4.rb
  tests/ruby/tests-data/example5.rb
  tests/ruby/tests-data/example_challenge.rb
  tests/ruby/tests-data/example_dependencies_not_okay_test8.rb
  tests/ruby/tests-data/example_fixed9.rb
  tests/ruby/tests-data/example_not_compile8.rb
  tests/ruby/tests-data/example_not_compile_test8.rb
  tests/ruby/tests-data/example_test7.rb
  tests/ruby/tests-data/example_test8.rb
  tests/ruby/tests-data/example_test9.rb
Labels: Team 1

#208 26 get all the go challenge
  app/go/views.py
Labels: Team 6

#213 Created Dependences module. Ref #186
  app/javascript/modules/dependences_module.py
Labels: Team 4

#216 Modification of command_module and CommandRunException. Ref #181
  app/javascript/exceptions/CommandRunException.py
  app/javascript/modules/command_module.py
Labels: Team 4

#217 created source_code_module. Ref #182
  app/javascript/modules/source_code_module.py
Labels: Team 4

#218 56 create post repair python challenge
  app/python/views.py
Labels: team 5

#221 220 ruby test special cases for post repair
  app/ruby/models.py
  app/ruby/rubychallengeapi.py
  app/ruby/rubychallengedao.py
  tests/ruby/test_rest_api.py
  tests/ruby/tests-data/example_fixed.rb
  tests/ruby/tests-data/example_fixed_syntax_error.rb
  tests/ruby/tests-data/example_test10.rb
  tests/ruby/tests-data/example_test11.rb
Labels: Team 1

#224 Class for file management. #196
  app/java/DAO_java_challenge.py
  app/java/controller.py
  app/java/file_management.py
  app/java/views.py
Labels: Team 3

#227 Class challenge for management. #197
  app/java/challenge.py
  app/java/controller.py
  app/java/views.py
Labels: Team 3

#229 the file_controller was created and the endpoints and some modules were modified. Ref #223
  app/javascript/controllers/files_controller.py
  app/javascript/create_challenge.py
  app/javascript/exceptions/CommandRunException.py
  app/javascript/exceptions/CompileJSException.py
  app/javascript/exceptions/FileReplaceException.py
  app/javascript/exceptions/FileUploadException.py
  app/javascript/files_controller.py
  app/javascript/get_challenge.py
  app/javascript/modules/source_code_module.py
  app/javascript/repair_chalenge.py
  app/javascript/update_challenge.py
Labels: Team 4

#235 30 make the method repair go challenge
  app/go/views.py
Labels: Team 6

#239 Add a directory for files for tests
  tests/go/files-for-tests/median.go
  tests/go/files-for-tests/median_solution_3point.go
  tests/go/files-for-tests/median_test.go
Labels: Team 6

#241 Closes #191 modularize python views in classes
  app/__init__.py
  app/python/PythonChallenge.py
  app/python/PythonChallengeDAO.py
  app/python/PythonController.py
  app/python/PythonSourceCode.py
  app/python/file_utils.py
  app/python/models.py
  app/python/subprocess_utils.py
  app/python/views.py
  migrations/versions/39219ee0bb7b_renaming_pythonchallenge_table_to_.py
  migrations/versions/785a27199c86_create_pythonchallenge_model.py
Labels: team 5

#246 #244 little fix modularization
  app/python/PythonChallenge.py
  app/python/PythonController.py
  app/python/subprocess_utils.py
Labels: team 5

#249 Java create repair
  app/java/DAO_java_challenge.py
  app/java/challenge.py
  app/java/challenge_candidate.py
  app/java/controller.py
  app/java/file_management.py
  app/java/views.py
Labels: Team 3

#250 Add a method post.
  app/go/views.py
Labels: Team 6

#242 199 ruby refactor put
  app/ruby/controller.py
  app/ruby/rubychallenge.py
  app/ruby/rubychallengeapi.py
  app/ruby/rubychallengedao.py
  app/ruby/rubycode.py
Labels: Team 1

#254 29 update a go challenge
  app/go/views.py
Labels: Team 6

#256 create and delete tmp directory to save files temporally. Ref #29
  app/go/views.py
Labels: Team 6

#255 200 ruby refactor method post repair
  app/ruby/controller.py
  app/ruby/repaircandidate.py
  app/ruby/rubychallenge.py
  app/ruby/rubychallengeapi.py
  app/ruby/rubycode.py
Labels: Team 1

#257 228 create c sharp src class
  app/cSharp/c_sharp_src.py
Labels: Team 2

#266 ref #261 challenge_dao turned into class and fixed bugs in methods
  app/javascript/dao/challenge_dao.py
Labels: Team 4

#271 118 ruby test special cases for put endpoint
  app/ruby/controller.py
  tests/ruby/test_rest_api.py
  tests/ruby/tests-data/example_challenge_new.rb
  tests/ruby/tests-data/example_fixed_no_compiles.rb
  tests/ruby/tests-data/example_not_compile.rb
  tests/ruby/tests-data/example_test12.rb
  tests/ruby/tests-data/example_test13.rb
  tests/ruby/tests-data/example_test14.rb
  tests/ruby/tests-data/example_test15.rb
  tests/ruby/tests-data/example_test16.rb
  tests/ruby/tests-data/example_test17.rb
  tests/ruby/tests-data/example_test18.rb
  tests/ruby/tests-data/example_test19.rb
  tests/ruby/tests-data/example_test20.rb
  tests/ruby/tests-data/example_test20new.rb
  tests/ruby/tests-data/example_test_no_compiles14.rb
Labels: Team 1

#274 Create chellenge api, delete views, modification __init__ Ref #262
  app/javascript/__init__.py
  app/javascript/api/javascript_challenge_api.py
  app/javascript/views.py
Labels: Team 4

#273 251 ruby adapt model to new structure
  app/__init__.py
  app/ruby/controller.py
  app/ruby/filemanagement.py
  app/ruby/models.py
  app/ruby/rubychallengeapi.py
  app/ruby/rubychallengedao.py
  app/ruby/rubychallengemodel.py
  migrations/versions/0cb84c718ecc_create_rubychallenge_model.py
  tests/ruby/test_db.py
Labels: Team 1

#276 173 js modularized
  app/javascript/__init__.py
  app/javascript/api/javascript_challenge_api.py
  app/javascript/controllers/challenge_controller.py
  app/javascript/controllers/challenge_repair_controller.py
  app/javascript/controllers/files_controller.py
  app/javascript/create_challenge.py
  app/javascript/dao/challenge_dao.py
  app/javascript/dependences.py
  app/javascript/doc/Diagrama.jpg
  app/javascript/exceptions/ChallengeRepairException.py
  app/javascript/exceptions/CommandRunException.py
  app/javascript/exceptions/FileReplaceException.py
  app/javascript/exceptions/FileUploadException.py
  app/javascript/exceptions/HTTPException.py
  app/javascript/exceptions/challenge_dao_exception.py
  app/javascript/files_js.py
  app/javascript/get_challenge.py
  app/javascript/list_challenges.py
  app/javascript/modules/command_module.py
  app/javascript/modules/dependences_module.py
  app/javascript/modules/source_code_module.py
  app/javascript/repair_chalenge.py
  app/javascript/update_challenge.py
  app/javascript/views.py
Labels: Team 4

#278 225 create c sharp challenge model class
  app/__init__.py
  app/cSharp/models.py
  app/cSharp/views.py
  migrations/versions/d33907401bd4_create_csharp_challenge_model.py
  migrations/versions/ecceabba75ad_rename_c_sharp__challenge_table_to_c_.py
Labels: Team 2

#283 167 python unit testing
  app/python/PythonChallengeDAO.py
  app/python/PythonController.py
  tests/python/__init__.py
  tests/python/example_programs_test/invalidProgram.py
  tests/python/test_endPoint_python.py
Labels: team 5

#289 Java add test db
  app/java/DAO_java_challenge.py
  tests/java/test_basics_db.py
Labels: Team 3

#297 295 c sharp test config
  tests/cSharp/__init__.py
  tests/cSharp/run-cSharp-tests.sh
  tests/cSharp/test-files/Example1.cs
  tests/cSharp/test-files/Example1Test.cs
  tests/cSharp/test_rest_api.py
Labels: Team 2

#301 C sharp general modularization
  app/cSharp/models.py
  app/cSharp/views.py
Labels: Team 2

#305 Add cleanup section on __init__. #295
  tests/cSharp/__init__.py
Labels: Team 2

#306 280 ruby return of the refactor
  app/ruby/controller.py
  app/ruby/repaircandidate.py
  app/ruby/rubychallenge.py
  app/ruby/rubychallengeapi.py
  app/ruby/rubychallengedao.py
  app/ruby/rubychallengemodel.py
  app/ruby/rubycode.py
  tests/ruby/test_rest_api.py
Labels: Team 1

#307 245 add python challenge dao to testdb
  tests/python/example_programs_test/code_not_compile.py
  tests/python/example_programs_test/test_not_compile.py
  tests/python/example_programs_test/valid_code.py
  tests/python/example_programs_test/valid_test_imp_valid_code.py
  tests/python/test_PythonChallengeDAO.py
Labels: team 5

#309 Give execute permission to run-cSharp-tests.py. #295
  tests/cSharp/run-cSharp-tests.sh
Labels: Team 2

#313 Add new files for use in testing. #295
  tests/cSharp/test-files/Example1.cs
  tests/cSharp/test-files/Example1Test.cs
  tests/cSharp/test-files/Example2.cs
  tests/cSharp/test-files/Example2Test.cs
  tests/cSharp/test-files/Example3.cs
  tests/cSharp/test-files/Example3Test.cs
  tests/cSharp/test-files/Example4.cs
  tests/cSharp/test-files/Example4Test.cs
  tests/cSharp/test_rest_api.py
Labels: Team 2

#314 292 post new challenge c sharp unit test
  tests/cSharp/test_rest_api.py
Labels: Team 2

#315 264 create go challenge dao class
  app/go/go_challenge_dao.py
  app/go/views.py
Labels: Team 6

#316 Add cleanup method. remove cleanup from init. #295
  tests/cSharp/__init__.py
  tests/cSharp/test_rest_api.py
Labels: Team 2

#317 Add test post api rest. #298
  app/java/challenge.py
  app/java/challenge_candidate.py
  app/java/file_management.py
  app/java/views.py
  tests/java/example_java/Prueba.java
  tests/java/example_java/PruebaTest.java
  tests/java/test_api_rest.py
Labels: Team 3

#318 Fix cleanup method. #295
  tests/cSharp/test_rest_api.py
Labels: Team 2

#319 243 create class python challenge repair
  app/python/PythonChallengeDAO.py
  app/python/PythonChallengeRepair.py
  app/python/PythonController.py
  app/python/PythonSourceCode.py
  app/python/views.py
Labels: team 5

#320 290 get all challenges endpoint unit testing
  tests/cSharp/test_rest_api.py
Labels: Team 2

#322 Add cleanup on init again. #295
  tests/cSharp/__init__.py
Labels: Team 2

#323 277 ruby create tests for rubychallengedao class
  tests/ruby/test_rubychallangedao.py
Labels: Team 1

#325 269 create go source code class
  app/go/go_src.py
  app/go/views.py
Labels: Team 6

#328 Add needed imports in init. Change test execution script. #295
  tests/cSharp/__init__.py
  tests/cSharp/run-cSharp-tests.sh
Labels: Team 2

#330 add cases test for post. #298
  tests/java/example_java/Nocompile.java
  tests/java/example_java/NocompileTest.java
  tests/java/example_java/Passalltest.java
  tests/java/example_java/Passalltesttest.java
  tests/java/example_java/Testfailclass.java
  tests/java/example_java/Testfailtest.java
  tests/java/test_api_rest.py
Labels: Team 3

#334 291 c# get challenge by id unit testing
  app/cSharp/models.py
  tests/cSharp/test_rest_api.py
Labels: Team 2

#335 265 create go challenge class
  app/go/go_challenge.py
Labels: Team 6

#338 Fix_in_put#189
  app/java/DAO_java_challenge.py
  app/java/challenge.py
  app/java/controller.py
  app/java/views.py
Labels: Team 3

#339 321 ruby the last refactor
  app/__init__.py
  app/ruby/__init__.py
  app/ruby/api.py
  app/ruby/controller.py
  app/ruby/models/rubychallengedao.py
  app/ruby/models/rubychallengemodel.py
  app/ruby/repaircandidate.py
  app/ruby/rubychallenge.py
  app/ruby/rubychallengeapi.py
  app/ruby/rubycode.py
  tests/ruby/test_rubychallangedao.py
Labels: Team 1

#340 310 merge new tests of update and post
  app/python/PythonChallenge.py
  tests/python/test_endPoint_python.py
Labels: team 5

#341 302 test python source code
  tests/python/example_programs_test/valid_code_3.py
  tests/python/test_python_source_code.py
Labels: team 5

#342 295 c sharp test config
  tests/cSharp/run-cSharp-tests.sh
  tests/cSharp/test-files/BaseExample.cs
  tests/cSharp/test-files/BaseTest.cs
  tests/cSharp/test-files/Example01.cs
  tests/cSharp/test-files/Example01Test.cs
  tests/cSharp/test-files/Example2Test.cs
  tests/cSharp/test-files/Example3.cs
  tests/cSharp/test-files/Example4Test.cs
  tests/cSharp/test-files/ExampleNoFails.cs
  tests/cSharp/test-files/ExampleSintaxErrors.cs
  tests/cSharp/test-files/TestSintaxErrors.cs
  tests/cSharp/test_rest_api.py
Labels: Team 2

#344 Java put challenge unit testing
  tests/java/test_api_rest.py
  tests/java/test_basics_db.py
Labels: documentation, Team 3

#345 332 fixing modularization bugs
  app/go/go_challenge.py
  app/go/go_src.py
Labels: Team 6

#346 343 ruby add robustness put dependencies
  app/ruby/controller.py
  app/ruby/models/rubychallengedao.py
  app/ruby/rubychallenge.py
  app/ruby/rubycode.py
Labels: Team 1

#347 310 more tests for update and repair, also fixed some bugs
  app/python/PythonChallenge.py
  app/python/PythonSourceCode.py
  app/python/views.py
  tests/python/example_programs_test/code_change_my_name_4.py
  tests/python/example_programs_test/code_repair_test_fail.py
  tests/python/example_programs_test/import_error_test.py
  tests/python/example_programs_test/test_change_my_name_4.py
  tests/python/test_endPoint_python.py
Labels: team 5

#348 Modified validation to check for ImportError during tests run #336
  app/python/subprocess_utils.py
Labels: team 5

#349 Use class methods on views. #228
  app/cSharp/c_sharp_src.py
  app/cSharp/views.py
Labels: Team 2

#350 226 create c sharp challenge class
  app/cSharp/c_sharp_challenge.py
  app/cSharp/views.py
Labels: Team 2

#351 293 post repair unit testing
  app/cSharp/c_sharp_src.py
  app/cSharp/views.py
  tests/cSharp/test-files/Example1Repair.cs
  tests/cSharp/test-files/ExampleNoFailsLonger.cs
  tests/cSharp/test_rest_api.py
Labels: Team 2

#352 Java put challenge unit testing
  tests/java/test_api_rest.py
Labels: Team 3

#353 304 ruby create extra tests for special cases
  app/ruby/controller.py
  tests/ruby/test_rest_api.py
  tests/ruby/tests-data/example_test21.rb
  tests/ruby/tests-data/example_test22.rb
  tests/ruby/tests-data/example_test23.rb
  tests/ruby/tests-data/example_test24.rb
  tests/ruby/tests-data/example_test25.rb
Labels: Team 1

#354 add test method repair. #331
  app/java/controller.py
  tests/java/example_java/Median.java
  tests/java/test_api_rest.py
Labels: Team 3

#359 fix in method repair and DAO
  app/java/DAO_java_challenge.py
  app/java/controller.py
Labels: Team 3

#364 230 create c sharp repair candidate class
  app/cSharp/c_sharp_repair_candidate.py
  app/cSharp/views.py
Labels: Team 2

#365 337 add name check for post and update
  app/python/PythonChallenge.py
  app/python/PythonController.py
  app/python/file_utils.py
Labels: team 5

#366 281 ruby refactor tests code
  app/ruby/controller.py
  tests/ruby/data_generator.py
  tests/ruby/test_gets_challenge.py
  tests/ruby/test_post_challenge.py
  tests/ruby/test_put_challenges.py
  tests/ruby/test_repair_challenges.py
  tests/ruby/test_rest_api.py
Labels: Team 1

#368 268 create repair candidate class
  app/go/go_challenge.py
  app/go/go_repair_candidate.py
Labels: Team 6

#372 295 c sharp test config
  tests/cSharp/__init__.py
  tests/cSharp/test_rest_api.py
  tests/cSharp/test_rest_api_get.py
  tests/cSharp/test_rest_api_post.py
  tests/cSharp/test_rest_api_put.py
  tests/cSharp/test_rest_api_repair_objetive.py
Labels: Team 2

#375 293 post repair unit testing
  tests/cSharp/test-files/ExampleNoFails2.cs
  tests/cSharp/test_rest_api_repair_objetive.py
Labels: Team 2

#369 310 add tests for endpoints
  app/python/views.py
  tests/python/atest_utils.py
  tests/python/example_programs_test/atest_change_my_name_4.py
  tests/python/example_programs_test/atest_not_compile.py
  tests/python/example_programs_test/code_repair_atest_fail.py
  tests/python/example_programs_test/import_error_atest.py
  tests/python/example_programs_test/valid_atest_1.py
  tests/python/example_programs_test/valid_atest_10.py
  tests/python/example_programs_test/valid_atest_11.py
  tests/python/example_programs_test/valid_atest_12.py
  tests/python/example_programs_test/valid_atest_13.py
  tests/python/example_programs_test/valid_atest_14.py
  tests/python/example_programs_test/valid_atest_15.py
  tests/python/example_programs_test/valid_atest_16.py
  tests/python/example_programs_test/valid_atest_17.py
  tests/python/example_programs_test/valid_atest_18.py
  tests/python/example_programs_test/valid_atest_19.py
  tests/python/example_programs_test/valid_atest_2.py
  tests/python/example_programs_test/valid_atest_20.py
  tests/python/example_programs_test/valid_atest_3.py
  tests/python/example_programs_test/valid_atest_4.py
  tests/python/example_programs_test/valid_atest_5.py
  tests/python/example_programs_test/valid_atest_6.py
  tests/python/example_programs_test/valid_atest_7.py
  tests/python/example_programs_test/valid_atest_8.py
  tests/python/example_programs_test/valid_atest_9.py
  tests/python/example_programs_test/valid_code_4.py
  tests/python/test_endPoint_python.py
  tests/python/test_get_endpoint.py
  tests/python/test_post_endpoint.py
  tests/python/test_post_repair_endpoint.py
  tests/python/test_put_endpoint.py
  tests/python/test_python_source_code.py
Labels: team 5

#376 Changes_test#367
  app/java/controller.py
  app/java/views.py
  tests/java/data_for_tests.py
  tests/java/test_api_rest.py
  tests/java/test_put_challenges.py
Labels: Team 3

#379 363 ruby add authentication system
  app/ruby/api.py
  app/ruby/controller.py
  app/ruby/models/rubychallengedao.py
  app/ruby/models/rubychallengemodel.py
  app/ruby/repaircandidate.py
  app/ruby/rubychallenge.py
  app/ruby/rubycode.py
  migrations/versions/0cb84c718ecc_create_rubychallenge_model.py
  tests/ruby/__init__.py
  tests/ruby/test_gets_challenge.py
  tests/ruby/test_post_challenge.py
  tests/ruby/test_put_challenges.py
  tests/ruby/test_repair_challenges.py
  tests/ruby/test_rubychallangedao.py
Labels: Team 1

#386 add player at response of repair
  app/java/controller.py
Labels: Team 3

#389 Add_migration_java_challenge#388
  app/java/models_java.py
  migrations/versions/73dfc71e91bd_challenge_java_model.py
Labels: Team 3

#390 231 c sharp model dao
  app/cSharp/c_sharp_challenge.py
  app/cSharp/c_sharp_challenge_DAO.py
  app/cSharp/c_sharp_src.py
  app/cSharp/models.py
  app/cSharp/views.py
Labels: Team 2

#391 263 create go controller class
  app/go/go_challenge.py
  app/go/go_challenge_dao.py
  app/go/go_controller.py
  app/go/go_directory_management.py
  app/go/go_repair_candidate.py
  app/go/go_src.py
  app/go/views.py
Labels: Team 6

#395 add attempts users in repair. #394
  app/java/DAO_java_challenge.py
  app/java/controller.py
Labels: Team 3

#399 294 put challenge unit testing
  app/cSharp/views.py
  tests/cSharp/__init__.py
  tests/cSharp/test_rest_api_put.py
Labels: Team 2

#401 fix range complexity the of challenges. #400
  app/java/DAO_java_challenge.py
  app/java/challenge.py
  tests/java/test_basics_db.py
Labels: Team 3

#403 fix_complexity_put
  app/java/controller.py
Labels: Team 3

#404 add_case_tests#296
  tests/java/test_put_challenges.py
Labels: Team 3

#405 add test the complexity in post
  tests/java/test_post_challenge.py
Labels: Team 3

#406 Fix test errors. #295
  app/cSharp/views.py
  tests/cSharp/test_rest_api_post.py
Labels: Team 2

#407 Add new c_sharp_attempts table. #373
  app/cSharp/models.py
  migrations/versions/4526c281a295_create_c_sharp_attempts_table.py
Labels: Team 2

#411 392 fix issues in methods
  app/go/go_challenge.py
  app/go/go_challenge_dao.py
  app/go/go_controller.py
  app/go/go_directory_management.py
  app/go/go_repair_candidate.py
  app/go/go_source_code.py
  app/go/views.py
  tests/go/files-for-tests/median2.go
  tests/go/files-for-tests/median2_test.go
  tests/go/tests_rest_api.py
Labels: Team 6

#412 Add authentication. #373
  app/cSharp/views.py
Labels: Team 2

#413 397 js implement attempt dao
  app/javascript/api/javascript_challenge_api.py
  app/javascript/controllers/challenge_repair_controller.py
  app/javascript/dao/attempt_dao.py
Labels: Team 4

#414 387 js add authentication
  app/javascript/api/javascript_challenge_api.py
  app/javascript/controllers/challenge_repair_controller.py
  app/javascript/models_js.py
  migrations/versions/18a04228b1db_javascript_attempts.py
  tests/javascript/__init__.py
Labels: Team 4

#416 378 update test authentication system
  app/python/views.py
  tests/python/__init__.py
  tests/python/atest_utils.py
  tests/python/test_get_endpoint.py
  tests/python/test_post_endpoint.py
  tests/python/test_post_repair_endpoint.py
  tests/python/test_put_endpoint.py
Labels: team 5

#417 370 add go authentication
  app/go/go_challenge_dao.py
  app/go/go_controller.py
  app/go/go_repair_candidate.py
  app/go/models_go.py
  app/go/views.py
  migrations/versions/7d84f03b8c37_add_a_table_go_attemps.py
  tests/go/__init__.py
  tests/go/tests_rest_api.py
Labels: Team 6

#418 393 ruby documentation
  app/ruby/__init__.py
  app/ruby/api.py
  app/ruby/controller.py
  app/ruby/docs/ruby-api-uml-diagram.png
  app/ruby/models/rubychallengedao.py
  app/ruby/models/rubychallengemodel.py
  app/ruby/repaircandidate.py
  app/ruby/rubychallenge.py
  app/ruby/rubycode.py
Labels: Team 1

#423 294 put challenge unit testing
  tests/cSharp/test-files/BaseExample3.cs
  tests/cSharp/test-files/BaseTest3.cs
  tests/cSharp/test_rest_api_put.py
Labels: Team 2

#427 Add case test, code cleaning and last details #426
  app/java/challenge.py
  app/java/challenge_candidate.py
  app/java/controller.py
  app/java/views.py
  tests/java/test_basics_db.py
  tests/java/test_post_challenge.py
  tests/java/test_put_challenges.py
Labels: Team 3

#430 292 post new challenge c sharp unit test
  app/cSharp/c_sharp_controller.py
  app/cSharp/views.py
  tests/cSharp/test_rest_api_post.py
Labels: Team 2

#432 Fix in methods and tests. #431
  app/java/challenge.py
  app/java/controller.py
  tests/java/test_basics_db.py
  tests/java/test_put_challenges.py
Labels: Team 3

#429 377 add authentication for python endpoints
  app/python/PythonChallengeDAO.py
  app/python/PythonChallengeRepair.py
  app/python/PythonController.py
  app/python/models.py
  app/python/views.py
  migrations/versions/39219ee0bb7b_renaming_pythonchallenge_table_to_.py
  tests/python/__init__.py
  tests/python/atest_utils.py
  tests/python/test_invalid_authorization.py
Labels: team 5

#434 428 fix go tests
  app/go/go_challenge.py
  app/go/go_challenge_dao.py
  app/go/go_controller.py
  app/go/go_repair_candidate.py
  app/go/views.py
  tests/go/__init__.py
  tests/go/tests_rest_api.py
Labels: Team 6

#433 415 js athentication testing
  tests/javascript/test_get_challenge.py
  tests/javascript/test_post_challenge.py
  tests/javascript/test_post_repair_challenge.py
  tests/javascript/test_put_challenge.py
Labels: Team 4

#435 147 js unit testing
  app/javascript/controllers/challenge_controller.py
  app/javascript/controllers/challenge_repair_controller.py
  app/javascript/controllers/files_controller.py
  app/javascript/dao/challenge_dao.py
  app/javascript/models_js.py
  app/javascript/modules/dependences_module.py
  app/javascript/modules/source_code_module.py
  tests/javascript/__init__.py
  tests/javascript/file_testing_folder/file_testing_folder_2/median.js
  tests/javascript/file_testing_folder/file_testing_folder_2/median.test.js
  tests/javascript/file_testing_folder/file_testing_folder_2/zip_testing.zip
  tests/javascript/file_testing_folder/median.js
  tests/javascript/file_testing_folder/median.test.js
  tests/javascript/file_testing_folder/nothing.js
  tests/javascript/file_testing_folder/test.js
  tests/javascript/test_challenge_controller.py
  tests/javascript/test_challenge_repair_controller.py
  tests/javascript/test_dao.py
  tests/javascript/test_db.py
  tests/javascript/test_dependence_module.py
  tests/javascript/test_files_controller.py
  tests/javascript/test_source_code_module.py
Labels: Team 4

#436 361 js endpoint testing
  app/javascript/api/javascript_challenge_api.py
  app/javascript/controllers/challenge_controller.py
  app/javascript/controllers/challenge_repair_controller.py
  app/javascript/controllers/files_controller.py
  app/javascript/dao/challenge_dao.py
  app/javascript/models_js.py
  app/javascript/modules/dependences_module.py
  app/javascript/modules/source_code_module.py
  example-challenges/javascript-challenges/example0.js
  example-challenges/javascript-challenges/example0.test.js
  example-challenges/javascript-challenges/example_not_exist.js
  example-challenges/javascript-challenges/example_not_exist.test.js
  example-challenges/javascript-challenges/example_pass_0.js
  example-challenges/javascript-challenges/example_pass_t.js
  example-challenges/javascript-challenges/example_pass_t.test.js
  example-challenges/javascript-challenges/medianCorrect.js
  example-challenges/javascript-challenges/medianCorrect.test.js
  example-challenges/javascript-challenges/medianNcp.js
  example-challenges/javascript-challenges/medianNcp.test.js
  example-challenges/javascript-challenges/median_not_compile.js
  example-challenges/javascript-challenges/median_not_compile.test.js
  tests/javascript/__init__.py
  tests/javascript/file_testing_folder/file_testing_folder_2/median.js
  tests/javascript/file_testing_folder/file_testing_folder_2/median.test.js
  tests/javascript/file_testing_folder/file_testing_folder_2/zip_testing.zip
  tests/javascript/file_testing_folder/median.js
  tests/javascript/file_testing_folder/median.test.js
  tests/javascript/file_testing_folder/nothing.js
  tests/javascript/file_testing_folder/test.js
  tests/javascript/test_challenge_controller.py
  tests/javascript/test_challenge_repair_controller.py
  tests/javascript/test_dao.py
  tests/javascript/test_db.py
  tests/javascript/test_dependence_module.py
  tests/javascript/test_files_controller.py
  tests/javascript/test_get_challenge.py
  tests/javascript/test_post_challenge.py
  tests/javascript/test_post_repair_challenge.py
  tests/javascript/test_put_challenge.py
  tests/javascript/test_source_code_module.py
Labels: Team 4

#438 294 put challenge unit testing
  app/cSharp/c_sharp_controller.py
  tests/cSharp/test_rest_api_put.py
Labels: Team 2

#441 422 sort tests by endpoints
  tests/go/tests_getAll_challenge.py
  tests/go/tests_getId_challenge.py
  tests/go/tests_post_challenge.py
  tests/go/tests_repair_challenge.py
  tests/go/tests_update_challenge.py
Labels: Team 6

#446 445 add tmp directory creation
  app/python/PythonController.py
  app/python/file_utils.py
Labels: team 5
